- name: configure db server
  hosts: db
  become: yes
  vars: 
    login_host: db.practdaws.online
  tasks:
  - name: Install MySQL server
    ansible.builtin.dnf:
      name: mysql-server
      state: latest
  - name: start and enable mysql mysql-server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  # check password is already setup or not
  - name: check DB connection
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      filter: version
      login_host: "{{ login_host }}"
    ignore_errors: yes
    register: mysql_connection_output

  - name: print output
    ansible.builtin.debug:
      msg: "output: {{ mysql_connection_output }}"